# Windows Server 2019
image: Visual Studio 2019

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\build-scripts\\run_with_compiler.cmd"
    SMB_SERVER: 127.0.0.1
    SMB_SHARE: share
    SMB_PORT: 445
  matrix:
  # https://www.appveyor.com/docs/installed-software/#python
  - PYTHON: Python27
  - PYTHON: Python27-x64
  - PYTHON: Python35
  - PYTHON: Python35-x64
  - PYTHON: Python36
  - PYTHON: Python36-x64
  - PYTHON: Python37
  - PYTHON: Python37-x64

init:
- ps: |
    $ErrorActionPreference = "Stop"
    # Override default Python version/architecture
    $env:Path="C:\$env:PYTHON;C:\$env:PYTHON\Scripts;$env:PATH"
    python -c "import platform; print('Python', platform.python_version(), platform.architecture()[0])"
    New-Item -Path C:\share -ItemType Directory > $null
    New-Item -Path C:\share-encrypted -ItemType Directory > $null
    New-SmbShare -Name $env:SMB_SHARE -Path C:\share -EncryptData $false -FullAccess Everyone > $null
    New-SmbShare -Name "$($env:SMB_SHARE)-encrypted" -Path C:\share-encrypted -EncryptData $true -FullAccess Everyone > $null

    $env:SMB_USER = $($env:USERNAME)
    $env:SMB_PASSWORD = [Microsoft.Win32.Registry]::GetValue("HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon", "DefaultPassword", '')

    Set-SmbServerConfiguration -RequireSecuritySignature $true -Force

install:
- cmd: python -m pip install --upgrade pip
- cmd: pip install --upgrade setuptools
- cmd: pip install -r requirements-test.txt
- cmd: pip install .

# test out pywin32 on some matrixes
- ps: |
    $ErrorActionPreference = "SilentlyContinue"
    if ($env:PYTHON -in @("Python27", "Python27-x64", "Python36", "Python36-x64")) {
        pip install .[kerberos]
    }
    $ErrorActionPreference = "Stop"

build: off  # Do not run MSBuild, build stuff at install step

test_script:
- cmd: py.test -v --pep8 --cov smbclient --cov smbprotocol --cov-report term-missing
